# Generated by Django 5.0.2 on 2024-09-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('summarizer_api', '0004_alter_usernotes_notetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_choice_text', models.TextField()),
                ('isAnswer', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Test Choice',
                'verbose_name_plural': 'Test Choices',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestQuestion', models.TextField()),
            ],
            options={
                'verbose_name': 'Test Question',
                'verbose_name_plural': 'Test Questions',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarizer_api.usernotes')),
                ('TestScore', models.IntegerField()),
                ('TestTotalScore', models.IntegerField()),
                ('TestDateCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Test',
                'verbose_name_plural': 'User Test',
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz_api.testchoices')),
            ],
            options={
                'verbose_name': 'Choice Answer',
                'verbose_name_plural': 'Choice Answers',
            },
        ),
        migrations.AddField(
            model_name='testchoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.testquestion'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.usertest'),
        ),
    ]
