# Generated by Django 5.0.2 on 2024-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='notesummary',
            field=models.TextField(blank=True, null=True, verbose_name='Note Summary'),
        ),
    ]
