# Generated by Django 5.0.2 on 2024-08-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards_api', '0001_initial'),
        ('summarizer_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflashcards',
            name='noteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizer_api.usernotes'),
        ),
    ]
