# Generated by Django 5.0.2 on 2024-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userflashcards',
            name='backCardText',
            field=models.CharField(default='', max_length=500, verbose_name='Back Card Text'),
        ),
    ]
