# Generated by Django 5.0.2 on 2024-08-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_time', models.PositiveIntegerField(default=25)),
                ('short_break', models.PositiveIntegerField(default=5)),
                ('long_break', models.PositiveIntegerField(default=15)),
                ('show_timer', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pomodoro',
                'verbose_name_plural': 'Pomodoro',
            },
        ),
    ]
