# Generated by Django 5.0.2 on 2024-08-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomodoro',
            options={'verbose_name': 'Pomodoro', 'verbose_name_plural': 'Pomodoro'},
        ),
    ]
