# Generated by Django 5.0.2 on 2024-08-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro_api', '0002_alter_pomodoro_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodoro',
            old_name='long_break',
            new_name='longBreak',
        ),
        migrations.RenameField(
            model_name='pomodoro',
            old_name='short_break',
            new_name='shortBreak',
        ),
        migrations.RenameField(
            model_name='pomodoro',
            old_name='show_timer',
            new_name='showTimer',
        ),
        migrations.RenameField(
            model_name='pomodoro',
            old_name='study_time',
            new_name='studyTime',
        ),
    ]
